### ISSUE TITLE
Table doesn't exist or not authorized when migrating from v0 to v1

### ISSUE THREAD

**Issue by charlesdong1991** [brooklyn-data/dbt_artifacts#249]
Hi, team, I am trying to follow the instruction here: https://github.com/brooklyn-data/dbt_artifacts#migrating-from-100-to-100

I completed the first step to create source tables. I am running the `dbt run-operation create_dbt_artifacts_tables` on old database -> Question: should I also run it on new database?

and then at the 2nd step, I am running
```
dbt --partial-parse run-operation migrate_from_v0_to_v1 --args '{old_database: metrics_db, old_schema: dbt_artifacts, new_database: metrics_dev, new_schema: dbt_artifacts}'
```

I receive an error below:
```
10:22:25  Migrating model_executions
10:22:28  Encountered an error while running operation: Database Error
  002003 (42S02): SQL compilation error:
  Table 'METRICS_DEV.DBT_ARTIFACTS.MODEL_EXECUTIONS' does not exist or not authorized.
```

Question 1: I know this table is not existing (which i thought would be what the migration is supposed to do?), but do I need to copy the table from old schema & database first to the new ones, before running this command? 

Question 2: This `model_executions` table was not in the v0 in `dbt_artifacts` schema in old database, only gets created via the step 1 and gets created in `public` schema. So also not sure why it is asking for this table?

Or what we should do to proceed in this case?

The new schema and database are created via Terraform, so schema and database exist, but no table of course. And if needed, we could also create tables the same way, but would like to understand how the migration is working?

Thank you very much and look forward to hearing back from you for any hints or support!! 🙇

**Comment by smitsrr** [comment]
When you upgrade you need to execute the new models as well, be sure to run `dbt run -m dbt_artifacts` to generate the models.

**Comment by charlesdong1991** [comment]
Hi, @smitsrr thank you very much for your reply! 

Does it mean that whenever I run something, e.g. `dbt run -m dbt_model_1`, I will need to run `dbt run -m dbt_artifacts` afterwards?

Another question is: what if my dbt command is `dbt test -m model_1`, then should we also need to add `dbt_artifacts` in the command?

**Comment by glsdown** [comment]
Hi @charlesdong1991 - thanks for reaching out. I'm really sorry it's taken so long to get back to you.

Were you able to resolve the issue with the migration to v1?

With regards to your follow up questions, you will need to run `dbt run --select dbt_artifacts` any time you want to update the package version such as in your example above. I have included instructions in #294 regarding this to try and clear things up. 

Once you have the tables built and updated, the `on-run-end` hook that you include in your `dbt_project.yml` file will then ensure the results are updated on each run:

```yml
on-run-end: "{{ dbt_artifacts.upload_results(results) }}"
```

**Comment by glsdown** [comment]
It looks like this is now resolved, so I'm going to close the issue. However, please do feel free to re-open it if I've closed it prematurely.
