### ISSUE TITLE
[Bug]: Runtime error since migration to dbt 1.9 (Object of type datetime is not JSON serializable)

### ISSUE THREAD

**Issue by D1111111** [brooklyn-data/dbt_artifacts#480]
## Overview

Error during `dbt compile` after I migrated from 1.8.2 to 1.9.0 dbt. <br />
dbt_artifacts version: 2.8.0
![Image](https://github.com/user-attachments/assets/4e22b9dc-0307-41c1-b8ec-10a2104cae85)

## How to reproduce

1. Migrate dbt to the latest version 1.9.0
2. Run `dbt compile`
3. An error is raised 
```Console result
2:57:33  Encountered an error:
Runtime Error
  Compilation Error in operation confirmation_transformation_dw-on-run-end-0 (.\dbt_project.yml)
    Object of type datetime is not JSON serializable
    > in macro upload_models (macros\upload_individual_datasets\upload_models.sql)
    > called by macro get_table_content_values (macros\upload_results\get_table_content_values.sql)
    > called by macro upload_results (macros\upload_results\upload_results.sql)
    > called by operation confirmation_transformation_dw-on-run-end-0 (.\dbt_project.yml)
```

## Environment

Results of running `dbt --version`:

```sh
Core:
  - installed: 1.9.2
  - latest:    1.9.2 - Up to date!

Plugins:
  - postgres: 1.9.0 - Up to date!
```

Please paste the contents of your `packages.yml` file here:

```yml
packages:
  - package: dbt-labs/dbt_utils
    version: 1.3.0

  - package: dbt-labs/codegen
    version: 0.13.1

  - package: calogica/dbt_expectations
    version: 0.10.4

  - package: calogica/dbt_date
    version: 0.10.1

  - package: brooklyn-data/dbt_artifacts
    version: 2.8.0
```

**Comment by D1111111** [comment]
This may be related to microbatches loading strategy since I use it, and that was the reason for migration to 1.9. 

Might be related to this bug: https://github.com/brooklyn-data/dbt_artifacts/issues/476

**Comment by D1111111** [comment]
The problem is [here](https://github.com/brooklyn-data/dbt_artifacts/blob/857193fbb375f1479451d6c6eabcb1b1b7f9b1b9/macros/upload_individual_datasets/upload_models.sql#L114-L118). When there is a microbatch materialized model, the `model_copy.config.begin` key gets datetime value, which can't be converted to json with dbt tojson directive.

One workaround is to replace the whole block with `null`. This will cause `all_results` column in the `models` table to be always empty.

**Comment by mtcarlone** [comment]
Hi all - please try to bump the version to 2.9.0 and see if that helps resolve the issue!
